language: php

php:
  - "7.1"
  - "7.2"
  - "hhvm"

env:
  - SYMFONY_VERSION=3.4

cache:
  directories:
    - vendor

before_script:
    - composer update
    - composer require --update-with-dependencies symfony/framework-bundle=~${SYMFONY_VERSION}.0 symfony/twig-bundle=~${SYMFONY_VERSION}.0

script: vendor/bin/phpunit --coverage-text
