language: php

php:
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"
  - "hhvm"

env:
  - SYMFONY_VERSION=2.5
  - SYMFONY_VERSION=2.6
  - SYMFONY_VERSION=2.7
  - SYMFONY_VERSION=2.8
  - SYMFONY_VERSION=3.0

matrix:
    exlude:
        - php: "5.3"
          env: SYMFONY_VERSION=3.0
        - php: "5.4"
          env: SYMFONY_VERSION=3.0

cache:
  directories:
    - vendor

before_script:
    - composer update
    - composer require --update-with-dependencies symfony/framework-bundle=~${SYMFONY_VERSION}.0 symfony/twig-bundle=~${SYMFONY_VERSION}.0

script: phpunit --coverage-text
